using System.Text.Json;
using WebExpress.LLM.Chat;

namespace WebExpress.LLM.Test.Chat;

/// <summary>
/// Validates the full Gemma-4 chat protocol produced by <see cref="ChatTemplate.ApplyTemplate"/>
/// against golden strings rendered from the reference <c>chat_template.jinja</c> (see
/// <c>Gemma4PromptGolden.json</c>, generated by <c>scratchpad/oracle.py</c>). Each scenario mirrors
/// the inputs used to produce the corresponding golden output, so the C# port is checked byte-for-byte
/// against the real template's behavior for system/thinking blocks, tool declarations, tool calls,
/// tool responses, multi-modal content, continuation, and thinking-strip.
/// </summary>
public sealed class UnitTestChatTemplateProtocol
{
    // ApplyTemplate reimplements the protocol in C#; the raw template content is not interpreted, so
    // any non-empty string satisfies the ChatTemplate constructor.
    private const string DummyTemplate = "{# reimplemented in C# #}";

    private static Dictionary<string, string>? _golden;

    private static Dictionary<string, string> Golden()
    {
        if (_golden == null)
        {
            var path = Path.Combine(AppContext.BaseDirectory, "Chat", "Gemma4PromptGolden.json");
            var json = File.ReadAllText(path);
            _golden = JsonSerializer.Deserialize<Dictionary<string, string>>(json)
                ?? throw new InvalidOperationException("Golden data could not be loaded.");
        }

        return _golden;
    }

    public static IEnumerable<object[]> ScenarioNames => Scenarios().Select(scenario => new object[] { scenario.Name });

    /// <summary>
    /// Asserts that every scenario's C# output matches the golden string rendered from the reference
    /// Jinja template.
    /// </summary>
    [Theory]
    [MemberData(nameof(ScenarioNames))]
    public void ApplyTemplate_MatchesReferenceTemplate(string name)
    {
        var scenario = Scenarios().Single(candidate => candidate.Name == name);
        var template = new ChatTemplate(DummyTemplate);

        var actual = template.ApplyTemplate(
            scenario.Messages,
            scenario.AddGenerationPrompt,
            scenario.Tools,
            scenario.EnableThinking);

        Assert.True(Golden().TryGetValue(name, out var expected), $"Missing golden entry for scenario '{name}'.");
        Assert.Equal(expected, actual);
    }

    /// <summary>
    /// Guards against drift between the C# scenario set and the golden data file.
    /// </summary>
    [Fact]
    public void Scenarios_CoverEveryGoldenEntry()
    {
        var scenarioNames = Scenarios().Select(scenario => scenario.Name).OrderBy(name => name).ToArray();
        var goldenNames = Golden().Keys.OrderBy(name => name).ToArray();

        Assert.Equal(goldenNames, scenarioNames);
    }

    private sealed record Scenario(
        string Name,
        IReadOnlyList<ChatMessage> Messages,
        bool AddGenerationPrompt = true,
        IReadOnlyList<ToolDefinition>? Tools = null,
        bool EnableThinking = false);

    private static Dictionary<string, object> Dict(params (string Key, object Value)[] entries)
    {
        var dictionary = new Dictionary<string, object>();
        foreach (var (key, value) in entries)
        {
            dictionary[key] = value;
        }

        return dictionary;
    }

    private static List<object> List(params object[] items) => items.ToList();

    private static ToolDefinition WeatherTool() => new("get_current_temperature")
    {
        Description = "Gets the current temperature for a location.",
        Parameters = Dict(
            ("type", "object"),
            ("properties", Dict(
                ("location", Dict(("type", "string"), ("description", "The city name, e.g. San Francisco"))),
                ("unit", Dict(("type", "string"), ("description", "Temperature unit"), ("enum", List("celsius", "fahrenheit")))))),
            ("required", List("location"))),
        Response = Dict(("description", "The temperature reading."), ("type", "OBJECT")),
    };

    private static ToolDefinition ArrayTool() => new("sum_values")
    {
        Description = "Sums a list of numbers.",
        Parameters = Dict(
            ("type", "object"),
            ("properties", Dict(
                ("values", Dict(("type", "array"), ("description", "Numbers to sum"), ("items", Dict(("type", "number"))))))),
            ("required", List("values"))),
    };

    private static ToolDefinition ObjectTool() => new("create_user")
    {
        Description = "Creates a user.",
        Parameters = Dict(
            ("type", "object"),
            ("properties", Dict(
                ("profile", Dict(
                    ("type", "object"),
                    ("description", "User profile"),
                    ("properties", Dict(
                        ("name", Dict(("type", "string"), ("description", "Full name"))),
                        ("age", Dict(("type", "integer"), ("description", "Age"), ("nullable", true))))),
                    ("required", List("name")))))),
            ("required", List("profile"))),
    };

    private static ToolDefinition ArrayObjectTool() => new("add_points")
    {
        Description = "Adds points.",
        Parameters = Dict(
            ("type", "object"),
            ("properties", Dict(
                ("points", Dict(
                    ("type", "array"),
                    ("description", "List of points"),
                    ("items", Dict(
                        ("type", "object"),
                        ("properties", Dict(
                            ("x", Dict(("type", "number"), ("description", "X coord"))),
                            ("y", Dict(("type", "number"), ("description", "Y coord"))))),
                        ("required", List("x", "y")))))))),
            ("required", List("points"))),
    };

    private static IEnumerable<Scenario> Scenarios()
    {
        yield return new Scenario("SingleUser", [new("user", "Hello")]);

        yield return new Scenario("UserAssistant", [new("user", "Hello"), new("assistant", "Hi there!")]);

        yield return new Scenario("SystemUser", [new("system", "You are helpful."), new("user", "Hello")]);

        yield return new Scenario("DeveloperUser", [new("developer", "System instructions."), new("user", "Hello")]);

        yield return new Scenario("MultiTurn",
        [
            new("system", "Be helpful."),
            new("user", "What is 2+2?"),
            new("assistant", "4"),
            new("user", "Thanks!"),
        ]);

        yield return new Scenario("ThinkingNoSystem", [new("user", "What is water?")], EnableThinking: true);

        yield return new Scenario("ThinkingWithSystem",
            [new("system", "You are helpful."), new("user", "What is water?")], EnableThinking: true);

        yield return new Scenario("Trimming", [new("system", "  Instructions  "), new("user", "  Hello  ")]);

        yield return new Scenario("NoGenerationPrompt", [new("user", "Hello")], AddGenerationPrompt: false);

        yield return new Scenario("Multimodal",
        [
            new("user", null!)
            {
                Parts = [ContentPart.FromText("Describe this:"), ContentPart.Image, ContentPart.Audio, ContentPart.Video],
            },
        ]);

        yield return new Scenario("StripThinkingModelContent",
        [
            new("user", "Hi"),
            new("assistant", "<|channel>thought\nlet me think\n<channel|>The answer is 4."),
        ]);

        yield return new Scenario("ToolsDeclaration", [new("user", "Weather in London?")], Tools: [WeatherTool()]);

        yield return new Scenario("ToolsArrayItems", [new("user", "Sum them")], Tools: [ArrayTool()]);

        yield return new Scenario("ToolsSystemThinking",
            [new("system", "You are helpful."), new("user", "Weather?")],
            Tools: [WeatherTool()], EnableThinking: true);

        yield return new Scenario("ToolCallLegacyResponse",
        [
            new("user", "Weather in London?"),
            new("assistant", "It is 15 and sunny.")
            {
                ToolCalls = [new ToolCall("get_current_temperature", Dict(("location", "London"), ("unit", "celsius")))],
                ToolResponses = [new ToolResponse("get_current_temperature", Dict(("temperature", 15), ("weather", "sunny")))],
            },
        ]);

        yield return new Scenario("ToolCallOpenAIResponse",
        [
            new("user", "Weather in London?"),
            new("assistant", null!)
            {
                ToolCalls = [new ToolCall("get_current_temperature", Dict(("location", "London"))) { Id = "call_1" }],
            },
            new("tool", "15 degrees, sunny") { ToolCallId = "call_1" },
            new("assistant", "It is 15 degrees and sunny."),
        ]);

        yield return new Scenario("ReasoningToolCall",
        [
            new("user", "Weather in London?"),
            new("assistant", null!)
            {
                Reasoning = "I should call the weather tool.",
                ToolCalls = [new ToolCall("get_current_temperature", Dict(("location", "London"))) { Id = "call_1" }],
            },
            new("tool", "15 degrees") { ToolCallId = "call_1" },
            new("assistant", "15 degrees."),
        ]);

        yield return new Scenario("ToolCallStringArgs",
        [
            new("user", "Weather?"),
            new("assistant", "done")
            {
                ToolCalls = [new ToolCall("get_current_temperature") { RawArguments = "location:<|\"|>London<|\"|>" }],
            },
        ]);

        yield return new Scenario("ConsecutiveAssistant",
            [new("user", "Hi"), new("assistant", "Part one. "), new("assistant", "Part two.")]);

        yield return new Scenario("NullContentUser", [new("user", null!)]);

        yield return new Scenario("SystemOnly", [new("system", "You are helpful.")]);

        yield return new Scenario("ToolCallComplexArgs",
        [
            new("user", "go"),
            new("assistant", "ok")
            {
                ToolCalls =
                [
                    new ToolCall("configure", Dict(
                        ("enabled", true),
                        ("disabled", false),
                        ("count", 3),
                        ("ratio", 1.5),
                        ("tags", List("a", "b")),
                        ("nested", Dict(("z", "last"), ("a", "first"))))),
                ],
            },
        ]);

        yield return new Scenario("ToolsNestedObject", [new("user", "make one")], Tools: [ObjectTool()]);

        yield return new Scenario("ToolsArrayOfObjects", [new("user", "add")], Tools: [ArrayObjectTool()]);

        yield return new Scenario("TwoTools", [new("user", "hi")], Tools: [WeatherTool(), ArrayTool()]);
    }
}
